### ISSUE TITLE
Kotlin: Not able to find the column with Int data type

### ISSUE THREAD

**Issue by rohegde7** [objectbox/objectbox-performance#11]
```
fun getTypeModel(typeId: Int): TypeModel? {
        return   App.getBox().query()
                              .equal(TypeModel_.type_id, typeId)
                              .build().findFirst()
}
```
The equal() method is not accpeting kotlin's Int data type for comparison. Anything I need to know regarding this?

**Comment by greenrobot-team** [comment]
`.equal(TypeModel_.type_id, typeId.toLong())` should work. -ut

**Comment by greenrobot-team** [comment]
Please note that this is the issue tracker for the ObjectBox performance testing app. Submit issues with ObjectBox at https://github.com/objectbox/objectbox-java
-ut
