### ISSUE TITLE
Feels incomplete without Isar

### ISSUE THREAD

**Issue by nawfalhasan** [objectbox/objectbox-performance#12]
Isar is another database that claims great performance. Without isar I feel this comparison is not complete.

**Comment by greenrobot-team** [comment]
[The Flutter benchmark app](https://github.com/objectbox/objectbox-dart-performance) has isar. But it may need some updating.

**Comment by nawfalhasan** [comment]
Is the result published anywhere?

**Comment by greenrobot-team** [comment]
We haven't published numbers for it in a while. So please run it yourself!
