### ISSUE TITLE
Add `LICENSE` file

### ISSUE THREAD

**Issue by jasonwyatt** [objectbox/objectbox-performance#3]
Looking through much of the code, it seems like the performance benchmark app is licensed under Apache 2.0.

It would be nice to have that explicitly called out in a `LICENSE` txt file in the root of the project (so github picks up on it)

**Comment by 87cobra** [comment]
Trying to remember this all, I will get right on that though, thanks bud.

**Comment by greenrobot-team** [comment]
Done.
